export interface Currency {
  name: string
  symbol: string
  code: string
}

export const currencies: Currency[] = [
  // Major global currencies
  { name: 'United States dollar', symbol: '$', code: 'USD' },
  { name: 'Euro', symbol: '€', code: 'EUR' },
  { name: 'British pound sterling', symbol: '£', code: 'GBP' },
  { name: 'Japanese yen', symbol: '¥', code: 'JPY' },
  { name: 'Indian rupee', symbol: '₹', code: 'INR' },
  { name: 'Australian dollar', symbol: 'A$', code: 'AUD' },
  { name: 'Canadian dollar', symbol: 'C$', code: 'CAD' },
  { name: 'Swiss franc', symbol: 'CHF', code: 'CHF' },
  { name: 'Chinese yuan', symbol: '¥', code: 'CNY' },
  { name: 'Singapore dollar', symbol: 'S$', code: 'SGD' },

  // Other Asian currencies
  { name: 'Hong Kong dollar', symbol: 'HK$', code: 'HKD' },
  { name: 'South Korean won', symbol: '₩', code: 'KRW' },
  { name: 'Malaysian ringgit', symbol: 'RM', code: 'MYR' },
  { name: 'Thai baht', symbol: '฿', code: 'THB' },
  { name: 'Indonesian rupiah', symbol: 'Rp', code: 'IDR' },
  { name: 'Philippine peso', symbol: '₱', code: 'PHP' },
  { name: 'Vietnamese dong', symbol: '₫', code: 'VND' },
  { name: 'Pakistani rupee', symbol: '₨', code: 'PKR' },
  { name: 'Bangladeshi taka', symbol: '৳', code: 'BDT' },
  { name: 'Sri Lankan rupee', symbol: 'Rs', code: 'LKR' },
  { name: 'Nepalese rupee', symbol: 'Rs', code: 'NPR' },
  { name: 'Kazakhstani tenge', symbol: '₸', code: 'KZT' },
  { name: 'Uzbekistani som', symbol: 'soʻm', code: 'UZS' },
  { name: 'Armenian dram', symbol: '֏', code: 'AMD' },
  { name: 'Azerbaijani manat', symbol: '₼', code: 'AZN' },
  { name: 'Georgian lari', symbol: '₾', code: 'GEL' },
  { name: 'Israeli new shekel', symbol: '₪', code: 'ILS' },
  { name: 'Saudi riyal', symbol: '﷼', code: 'SAR' },
  { name: 'United Arab Emirates dirham', symbol: 'د.إ', code: 'AED' },
  { name: 'Qatari riyal', symbol: 'ر.ق', code: 'QAR' },
  { name: 'Kuwaiti dinar', symbol: 'د.ك', code: 'KWD' },
  { name: 'Omani rial', symbol: 'ر.ع.', code: 'OMR' },
  { name: 'Bahraini dinar', symbol: '.د.ب', code: 'BHD' },
  { name: 'Iraqi dinar', symbol: 'ع.د', code: 'IQD' },
  { name: 'Jordanian dinar', symbol: 'د.ا', code: 'JOD' },
  { name: 'Lebanese pound', symbol: 'ل.ل', code: 'LBP' },
  { name: 'Syrian pound', symbol: '£S', code: 'SYP' },
  { name: 'Yemeni rial', symbol: '﷼', code: 'YER' },

  // African currencies
  { name: 'South African rand', symbol: 'R', code: 'ZAR' },
  { name: 'Egyptian pound', symbol: 'E£', code: 'EGP' },
  { name: 'Nigerian naira', symbol: '₦', code: 'NGN' },
  { name: 'Kenyan shilling', symbol: 'KSh', code: 'KES' },
  { name: 'Ethiopian birr', symbol: 'Br', code: 'ETB' },
  { name: 'Ghanaian cedi', symbol: '₵', code: 'GHS' },
  { name: 'Moroccan dirham', symbol: 'د.م.', code: 'MAD' },
  { name: 'Tanzanian shilling', symbol: 'TSh', code: 'TZS' },
  { name: 'Algerian dinar', symbol: 'د.ج', code: 'DZD' },
  { name: 'Angolan kwanza', symbol: 'Kz', code: 'AOA' },
  { name: 'Botswana pula', symbol: 'P', code: 'BWP' },
  { name: 'Libyan dinar', symbol: 'ل.د', code: 'LYD' },
  { name: 'Mauritian rupee', symbol: '₨', code: 'MUR' },
  { name: 'Namibian dollar', symbol: 'N$', code: 'NAD' },
  { name: 'Rwandan franc', symbol: 'FRw', code: 'RWF' },
  { name: 'Tunisian dinar', symbol: 'د.ت', code: 'TND' },
  { name: 'Ugandan shilling', symbol: 'USh', code: 'UGX' },
  { name: 'Zambian kwacha', symbol: 'ZK', code: 'ZMW' },
  { name: 'Zimbabwean dollar', symbol: 'Z$', code: 'ZWL' },

  // European currencies (non-Euro)
  { name: 'Swedish krona', symbol: 'kr', code: 'SEK' },
  { name: 'Norwegian krone', symbol: 'kr', code: 'NOK' },
  { name: 'Danish krone', symbol: 'kr', code: 'DKK' },
  { name: 'Polish złoty', symbol: 'zł', code: 'PLN' },
  { name: 'Hungarian forint', symbol: 'Ft', code: 'HUF' },
  { name: 'Czech koruna', symbol: 'Kč', code: 'CZK' },
  { name: 'Romanian leu', symbol: 'lei', code: 'RON' },
  { name: 'Bulgarian lev', symbol: 'лв', code: 'BGN' },
  { name: 'Croatian kuna', symbol: 'kn', code: 'HRK' },
  { name: 'Serbian dinar', symbol: 'дин', code: 'RSD' },
  { name: 'Russian ruble', symbol: '₽', code: 'RUB' },
  { name: 'Ukrainian hryvnia', symbol: '₴', code: 'UAH' },
  { name: 'Belarusian ruble', symbol: 'Br', code: 'BYN' },
  { name: 'Turkish lira', symbol: '₺', code: 'TRY' },
  { name: 'Icelandic króna', symbol: 'kr', code: 'ISK' },
  { name: 'Albanian lek', symbol: 'L', code: 'ALL' },
  { name: 'Macedonian denar', symbol: 'ден', code: 'MKD' },
  { name: 'Moldovan leu', symbol: 'L', code: 'MDL' },
  { name: 'Bosnia and Herzegovina convertible mark', symbol: 'KM', code: 'BAM' },

  // North & Central American currencies
  { name: 'Mexican peso', symbol: '$', code: 'MXN' },
  { name: 'Costa Rican colón', symbol: '₡', code: 'CRC' },
  { name: 'Guatemalan quetzal', symbol: 'Q', code: 'GTQ' },
  { name: 'Honduran lempira', symbol: 'L', code: 'HNL' },
  { name: 'Nicaraguan córdoba', symbol: 'C$', code: 'NIO' },
  { name: 'Panamanian balboa', symbol: 'B/.', code: 'PAB' },
  { name: 'Dominican peso', symbol: 'RD$', code: 'DOP' },
  { name: 'Jamaican dollar', symbol: 'J$', code: 'JMD' },
  { name: 'Bahamian dollar', symbol: 'B$', code: 'BSD' },
  { name: 'Barbadian dollar', symbol: 'Bds$', code: 'BBD' },
  { name: 'Bermudian dollar', symbol: 'BD$', code: 'BMD' },
  { name: 'Eastern Caribbean dollar', symbol: 'EC$', code: 'XCD' },
  { name: 'Cuban peso', symbol: '$', code: 'CUP' },
  { name: 'Cayman Islands dollar', symbol: 'CI$', code: 'KYD' },
  { name: 'Trinidad and Tobago dollar', symbol: 'TT$', code: 'TTD' },

  // South American currencies
  { name: 'Brazilian real', symbol: 'R$', code: 'BRL' },
  { name: 'Argentine peso', symbol: '$', code: 'ARS' },
  { name: 'Colombian peso', symbol: '$', code: 'COP' },
  { name: 'Chilean peso', symbol: '$', code: 'CLP' },
  { name: 'Peruvian sol', symbol: 'S/', code: 'PEN' },
  { name: 'Venezuelan bolívar soberano', symbol: 'Bs.S', code: 'VES' },
  { name: 'Bolivian boliviano', symbol: 'Bs.', code: 'BOB' },
  { name: 'Paraguayan guaraní', symbol: '₲', code: 'PYG' },
  { name: 'Uruguayan peso', symbol: '$U', code: 'UYU' },
  { name: 'Guyanese dollar', symbol: 'G$', code: 'GYD' },
  { name: 'Surinamese dollar', symbol: '$', code: 'SRD' },

  // Oceania/Pacific currencies
  { name: 'New Zealand dollar', symbol: 'NZ$', code: 'NZD' },
  { name: 'Fijian dollar', symbol: 'FJ$', code: 'FJD' },
  { name: 'CFP franc', symbol: '₣', code: 'XPF' },
  { name: 'Solomon Islands dollar', symbol: 'SI$', code: 'SBD' },
  { name: 'Vanuatu vatu', symbol: 'VT', code: 'VUV' },
  { name: 'Samoan tālā', symbol: 'T', code: 'WST' },
  { name: 'Tongan paʻanga', symbol: 'T$', code: 'TOP' },
  { name: 'Papua New Guinean kina', symbol: 'K', code: 'PGK' },

  // Special cases and regional currencies
  { name: 'East Caribbean dollar', symbol: 'EC$', code: 'XCD' },
  { name: 'West African CFA franc', symbol: 'CFA', code: 'XOF' },
  { name: 'Central African CFA franc', symbol: 'FCFA', code: 'XAF' },
  { name: 'Comorian franc', symbol: 'CF', code: 'KMF' },
  { name: 'Djiboutian franc', symbol: 'Fdj', code: 'DJF' },
  { name: 'Eritrean nakfa', symbol: 'Nfk', code: 'ERN' },
  { name: 'Malagasy ariary', symbol: 'Ar', code: 'MGA' },
  { name: 'Mauritanian ouguiya', symbol: 'UM', code: 'MRU' },
  { name: 'São Tomé and Príncipe dobra', symbol: 'Db', code: 'STN' },
  { name: 'Seychellois rupee', symbol: '₨', code: 'SCR' },
  { name: 'Sudanese pound', symbol: 'ج.س.', code: 'SDG' },
  { name: 'Tajikistani somoni', symbol: 'SM', code: 'TJS' },
  { name: 'Turkmenistani manat', symbol: 'm', code: 'TMT' },
  { name: 'Afghan afghani', symbol: '؋', code: 'AFN' },
  { name: 'Bhutanese ngultrum', symbol: 'Nu.', code: 'BTN' },
  { name: 'Cambodian riel', symbol: '៛', code: 'KHR' },
  { name: 'North Korean won', symbol: '₩', code: 'KPW' },
  { name: 'Mongolian tögrög', symbol: '₮', code: 'MNT' },
  { name: 'Myanmar kyat', symbol: 'Ks', code: 'MMK' },
  { name: 'Laotian kip', symbol: '₭', code: 'LAK' },
  { name: 'Maldivian rufiyaa', symbol: 'Rf', code: 'MVR' },
  { name: 'Nepalese rupee', symbol: '₨', code: 'NPR' }
  // { name: 'Palauan dollar', symbol: '$', code: 'USD' }, // Uses USD
  // { name: 'Tibetan ngultrum', symbol: 'Nu.', code: 'BTN' }, // Uses BTN
  // { name: 'Tuvaluan dollar', symbol: '$', code: 'AUD' }, // Uses AUD
  // { name: 'Cook Islands dollar', symbol: '$', code: 'NZD' }, // Uses NZD
  // { name: 'Niue dollar', symbol: '$', code: 'NZD' }, // Uses NZD
  // { name: 'Pitcairn Islands dollar', symbol: '$', code: 'NZD' }, // Uses NZD
]
